```mermaid
flowchart LR
    Index[index.ts] --> Defaults
    Index --> Signal
    Index --> Socket
    Index --> Types
    Index --> Utils
    Index --> WABinary
    Index --> WAM
    Index --> WAUSync
```
